//BLACKJACK GAME
#include<iostream> // For cin and cout
#include<fstream> // For file manipulation.
#include<stdlib.h>
#include<process.h>
#include<time.h> // For generating random numbers.
using namespace std;

main()
{
    fstream file;
    char a, name[30], n[30], in[1000], crd[1000];
    long p, money, c, pl, sp, j, i, op, s;

    // A simple loading screen
    for(i=0;i<=100;++i)
    {
        cout<<"\n\n\n\n\t\t\t\t LOADING "<<i<<" %";
        system("cls");
    }

    do
    {
        system("cls");
        cout<<"\n   |---|   |       |---|   |---|   |   /       |   |---|   |---|   |   /   ";
        cout<<"\n   |   |   |       |   |   |       |  /        |   |   |   |       |  /    ";
        cout<<"\n   |   |   |       |   |   |       | /         |   |   |   |       | /     ";
        cout<<"\n   |---|   |       |---|   |       | \\         |   |---|   |       | \\    ";
        cout<<"\n   |   |   |       |   |   |       |  \\        |   |   |   |       |  \\   ";
        cout<<"\n   |---|   |---|   |   |   |---|   |   \\   |---|   |   |   |---|   |   \\  ";
        cout<<"\n"<<"\n";
        cout<<"\n 1.Play Game.";
        cout<<"\n 2.High Score.";
        cout<<"\n 3.Instruction.";
        cout<<"\n 4.Quit.";
        cout<<"\n 5.Credits.";
        cout<<"\n Please select an option (1-5) : ";
        cin>>op;
        switch(op)
        {
            case 1:
                cout<<"\n 1.Play Game.";
                do
                {
                    p=0;
                    cout<<"\n Enter the name : ";
                    cin>>name;
                    for(i=0;i<10;++i)
                    {
                        do
                        {
                            cout<<"\n Enter money to bet (0-10000 $) : ";
                            cin>>money;
                            if(money>10000)
                            {
                                // This sections is there to prevent overflow of integer variable.
                                cout<<"\n Can't handle that munch amount of money.";
                                cout<<"\n Please enter again.";
                            }
                        }while(money>10000);
                        srand(time(NULL));  // Initialize random function
                        for(j=0;j<5;++j)
                        {
                            c=rand() % 5 + 1; // Generate random number
                        }
                        cout<<"\n Enter a number (1-5) : ";
                        cin>>pl;
                        if(pl==c)
                        {
                            // Check if the number entered by the player is equal to the number generated by program.
                            cout<<"\n Correct.You have "<<10-(i+1)<<" trys left.";
                            p=p+money;
                            cout<<"\n Current score is : "<<p<<"$";
                            cout<<"\n Do you want to take the money and run (y/n) : ";
                            cin>>a;
                            if(a=='y'||a=='Y')
                                break;
                            else
                                continue;
                        }
                        else
                        {
                            // If the players number is not equal to the number generated by program.
                            cout<<"\n Incorrect.You have "<<10-(i+1)<<" trys.";
                            p=p-money;
                            cout<<"\n Current score is : "<<p<<"$";
                            cout<<"\n Do you want to take the money and run (y/n) : ";
                            cin>>a;
                            if(a=='y'||a=='Y')
                                break;
                            else
                                continue;
                        }
                    }
                    // Check if current score is more than high score.
                    cout<<"\n"<<" "<<name<<" your score is "<<p<<"$";
                    file.open("Score.txt",ios::in|ios::out);
                    file>>sp;
                    if(p>=sp)
                    {
                        // If so write th new score to file.
                        file.close();
                        file.open("Score.txt",ios::in|ios::out|ios::trunc);
                        file<<p<<'\n'<<name;
                        cout<<"\n CONGRATS NEW HIGH SCORE.";
                        file.close();
                    }
                    file.close();
                    cout<<"\n Want to play again (y/n) : ";
                    cin>>a;
                }while(a=='y'||a=='Y');
            break;
            case 2:
                // Show high score
                cout<<"\n 2.High Score.";
                file.open("Score.txt",ios::in|ios::out);
                file>>s;
                file>>n;
                file.close();
                cout<<"\n Name : "<<n;
                cout<<"\n High score : "<<s<<"$";
            break;
            case 3:
                // Show instructions
                cout<<"\n 3.Instruction. \n";
                file.open("Instructions.txt",ios::in|ios::out);
                file.getline(in,1000,'#');
                cout<<in<<endl;
                file.close();
            break;
            case 4:
                // Quit game
                cout<<"\n 4.Quit.";
                exit(0);
            break;
            case 5:
                // Show credits
                cout<<"\n 5.Credits. \n";
                file.open("Credits.txt",ios::in|ios::out);
                file.getline(crd,1000,'#');
                cout<<crd<<endl;
                file.close();
            break;
            default:
                cout<<"\n Wrong choice.";
            break;
    }
    cout<<"\n Go back to main menu (y/n) : ";
    cin>>a;
    }while(a=='y'||a=='Y');
    exit(0);
}




